import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import Header from "@/components/dashboard/Header";



const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-urbanist",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${urbanist.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
